
[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "20"
PLAYWRIGHT_BROWSERS_PATH = "0"


[[redirects]]
from = "/2024/interaction-and-design-rules/src"
to = "https://github.com/antfu/talks/tree/main/2024-10-29"
status = 302

[[redirects]]
from = "2024-10-29"
to = "https://talks.antfu.me/2024/interaction-and-design-rules/"
status = 301

[[redirects]]
from = "/2024/interaction-and-design-rules/*"
to = "/2024/interaction-and-design-rules/index.html"
status = 200

[[redirects]]
from = "/"
to = "https://vidorra.life/talks"
status = 302
